Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
""" URL patterns for blogs """

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
	# Home page
	path('', views.blogposts, name='blogposts'),
	# 
	path('new_post/', views.new_post, name='new_post'),
	# 
	path('edit_post/<int:post_id>/', views.edit_post, name='edit_post')
]

users/urls.py
""" URL patterns for users """

from django.urls import include, path

from . import views

app_name = 'users'
urlpatterns = [
	# Auth url for default
	path('', include('django.contrib.auth.urls')),
	# Registration
	path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
	""" Post of the user """
	title = models.CharField(max_length=200)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		""" Return string representation """
		return f"{self.title}:  {self.text}"

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class PostForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields = ['title', 'text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render, redirect, get_objects_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404


from .models import BlogPost
from .forms import PostForm

def blogposts(request):
	""" Display topic """
	blogposts = BlogPost.objects.order_by('date_added')
	context = {'blogposts': blogposts}
	return render(request, 'blogs/index.html', context)

@login_required
def new_post(request):
	""" Adding new post """
	if request.method != 'POST':
		# Empty
		form = PostForm()
	else:
		# POST
		form = PostForm(data=request.POST)
		if form.is_valid():
			new_post = form.save(commit=False)
			new_post.owner = request.user
			new_post.save()
			return redirect('blogs:blogposts')
	
	context = {'form': form}
	return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
	""" Edit existing post """
	post = get_objects_or_404(BlogPost, id=post_id)
	# Ensure user is owner
	if post.owner != request.user:
		raise Http404

	if request.method != 'POST':
		# Fills form by data of current post
		form = PostForm(instance=post)
	else:
		form = PostForm(instance=post, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('blogs:blogposts')

	context = {'post': post, 'form': form}
	return render(request, 'blogs/edit_post.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
	""" Register new user """
	if request.method != 'POST':
		form = UserCreationForm()
	else:
		# Process form
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			# login and redirect to home
			login(request, new_user)
			return redirect('blogs:blogposts')

	context = {'form': form}
	return render(request, 'users/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, 
      initial-scale=1, shrink-to-fit=no">
    <title>Blog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

  </head>
  <body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

      <a class="navbar-brand" href="{% url 'blogs:blogposts' %}">Blogs</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text">Hello, {{ user.username }}. </span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
          {% endif %}
        </ul>
      </div>

    </nav>

    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>

</body>

</html>

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Editing</h2>
{% endblock page_header %}

{% block content %}

  <p><a href="{% url 'blogs:blogposts' %}">Posts</a></p>

  <form action="{% url 'blogs:edit_post' post.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
  	{% buttons %}
  	  <button name='submit' class="btn btn-primary">save changes</button>
  	{% endbuttons %}
  </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
    <h1>Posts</h1>
    <a href="{% url 'blogs:new_post' %}">Add a new post</a>
{% endblock page_header %}

{% block content %}
  
    {% for post in blogposts %}
      <div class="card mb-3">
        <h4 class="card-header">
          {{ post.title|linebreaks }}
        </h4>
        <div class="card-header">
          {{ post.text|linebreaks }}
          {{ post.date_added|date:'M d, Y H:i' }} 
          <a href="{% url 'blogs:edit_post' post.id %}">Edit post</a>
        </div>
      </div>

    {% empty %}
      <li>No posts have been added yet.</li>
    {% endfor %}

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>New post</h2>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'blogs:new_post' %}" method='post' class="form">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	{% buttons %}
  	  <button name="submit" class="btn btn-primary">add post</button>
    {% endbuttons %}
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Register new account</h2>
{% endblock page_header %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}" class="form">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	{% buttons %}
  	  <button name="submit" class="btn btn-primary">Register</button>
  	{% endbuttons %}
  	<input type='hidden' name='next' value='{% url "blogs:blogposts" %}' />

  </form>

{% endblock content %}